"""The version is one number, and every claim about it is checked.

There are three places a version can be read from this project: `pyproject.toml`
declares the distribution's, `phone_control.__version__` is what the package reports,
and the MCP server announces one to every client that mounts it. Two of those were
hand-maintained copies until the release milestone, which is a chain whose strength is
the weakest link nobody looks at — and the server's copy was the one a *client* sees.

The test that this file replaces nothing of: `tests/test_the_server_can_be_mounted.py`
checks what a mounted client is told, because that is where the announcement is made.
"""

from __future__ import annotations

import tomllib
from pathlib import Path

import pytest

import phone_control

REPOSITORY_ROOT = Path(__file__).resolve().parent.parent


def the_declared_version() -> str:
    manifest = tomllib.loads((REPOSITORY_ROOT / "pyproject.toml").read_text())
    return manifest["project"]["version"]


def test_the_distribution_and_the_package_agree():
    """`pyproject.toml` and `__version__`, which are two files and one fact."""
    declared, reported = the_declared_version(), phone_control.__version__

    assert declared == reported, (
        f"pyproject.toml says {declared!r} and phone_control.__version__ says "
        f"{reported!r}. The version a client is told comes from the package, and the "
        f"version an installer resolves comes from the manifest, so these drifting "
        f"apart means two different answers about which release is running."
    )


def test_the_version_is_written_down_in_exactly_two_places():
    """A copy of the version in any other file is a copy that can go stale.

    Written as a search rather than a list of known offenders, so that reintroducing
    the literal in a third file fails here rather than at the next release.
    """
    version = phone_control.__version__
    allowed = {
        Path("pyproject.toml"),
        Path("src/phone_control/__init__.py"),
        # The lockfile records the distribution by name and version, and is
        # regenerated by `uv lock` rather than edited, which is the point of it.
        Path("uv.lock"),
        # The MCP Registry entry has to carry the version itself: the registry reads
        # the file, not the package. It is a copy, so it is checked rather than
        # trusted - `tests/test_the_registry_entry_is_true.py` fails when it differs,
        # and the release workflow refuses a tag that disagrees with it.
        Path("server.json"),
    }

    found = []
    for path in sorted(REPOSITORY_ROOT.rglob("*")):
        relative = path.relative_to(REPOSITORY_ROOT)
        if relative in allowed or not path.is_file():
            continue
        if any(
            part in {".git", ".venv", "__pycache__", "dist", "artifacts"}
            for part in relative.parts
        ):
            continue
        if path.suffix not in {".py", ".toml", ".yaml", ".yml", ".md", ".sh", ".json"}:
            continue
        if version in path.read_text(encoding="utf-8", errors="ignore"):
            found.append(str(relative))

    assert not found, (
        f"{version} is written out in {found}. It belongs in pyproject.toml and\n"
        f"src/phone_control/__init__.py, and anywhere else it appears can be read "
        f"from phone_control.__version__ instead. A release that bumps one and not "
        f"the other ships an artifact that disagrees with itself."
    )


@pytest.mark.parametrize("part", ["major", "minor", "patch"])
def test_the_version_has_the_three_parts_a_release_needs(part):
    """A version a tag can be checked against: `vX.Y.Z` and nothing imaginative."""
    pieces = phone_control.__version__.split(".")
    assert len(pieces) == 3, f"the version is {phone_control.__version__!r}"
    assert all(piece.isdigit() for piece in pieces), (
        f"the {part} part of {phone_control.__version__!r} is not a number"
    )
